const CONVERSATION_STATES = Object.freeze({
  START: 'START',
  SELECT_LANGUAGE: 'SELECT_LANGUAGE',
  COLLECT_NAME: 'COLLECT_NAME',
  COLLECT_AGE: 'COLLECT_AGE',
  COLLECT_GENDER: 'COLLECT_GENDER',
  COLLECT_LOCATION: 'COLLECT_LOCATION',
  COLLECT_SYMPTOMS: 'COLLECT_SYMPTOMS',
  COMPLETED: 'COMPLETED',
  IVR_LANGUAGE_SELECTION: 'IVR_LANGUAGE_SELECTION',
  IVR_COLLECT_NAME: 'IVR_COLLECT_NAME',
  IVR_COLLECT_AGE: 'IVR_COLLECT_AGE',
  IVR_COLLECT_GENDER: 'IVR_COLLECT_GENDER',
  IVR_COLLECT_LOCATION: 'IVR_COLLECT_LOCATION',
  IVR_COLLECT_SYMPTOMS: 'IVR_COLLECT_SYMPTOMS',
  IVR_CONFIRM: 'IVR_CONFIRM',
  IVR_COMPLETED: 'IVR_COMPLETED'
});

module.exports = { CONVERSATION_STATES };
