const CONVERSATION_STATES = Object.freeze({
  START: 'START',
  SELECT_LANGUAGE: 'SELECT_LANGUAGE',
  COLLECT_NAME: 'COLLECT_NAME',
  COLLECT_AGE: 'COLLECT_AGE',
  COLLECT_GENDER: 'COLLECT_GENDER',
  COLLECT_LOCATION: 'COLLECT_LOCATION',
  COLLECT_SYMPTOMS: 'COLLECT_SYMPTOMS',
  COMPLETED: 'COMPLETED'
});

module.exports = { CONVERSATION_STATES };
